export interface UserEntity {
  id: string;
  firebaseUid: string;
  email: string;
  gender?: string;
  age?: number;
  height?: number;
  currentWeight?: number;
  bmiStatus?: string;
  goal?: string;
  bodyType?: string;
  targetWeight?: number;
  dreamBodyShape?: string;
  focusOn: string[];
  workoutExperiance?: string;
  fitness?: string;
  self_assessed_activity?: string;
  knee?: boolean;
  squat_reps?: string;
  pushups_reps?: string;
  crunches_reps?: string;
  plank_reps?: string;
  walk_daily?: string;
  badHabit: string[];
  lifeStyle?: string;
  idealWeight?: string;
  sleepTime?: string;
  GetupTime?: string;
  wakeupTime?: string;
  feelStressed?: string;
  motivate: string[];
  workOutPlace: string[];
  excludeloud?: string;
  eventcomingup?: string;
  eventTime?: string;
  commitTime?: string;
  LengthWorkout?: number;
  profileName?: string;
  profileImage?: string;
  planPace?: string;
  trainingDays: string[];
  remainders: boolean;
  hearAbout?: string;
  subscriptionStatus: string;
  subscriptionExpiry?: Date;
  workoutDuration: string;
  warmupDuration: string;
  recoveryDuration: string;
  createdAt: string | Date;
  updatedAt: string | Date;
}
export interface UserUpdateEntity {
  trainingDays: string[];
  workoutDuration: string;
  warmupDuration: string;
  recoveryDuration: string;
  gender?: string;
  height?: number;
  goal?: string;
  knee?: boolean;
  profileImage?: string;
}
